version: 2

jobBase: &jobBase
  working_directory: /go/src/github.com/abice/gencheck
  steps:
      - checkout
      - run:
          name: Build
          command: |
            make build
      - run:
          name: Test
          command: |
            make test
            make cover
            make coveralls

jobs:
  golang_1.11:
    <<: *jobBase
    docker:
      - image: circleci/golang:1.11
  golang_1.12:
    <<: *jobBase
    docker:
      - image: circleci/golang:1.12
  golang_1.13:
    <<: *jobBase
    docker:
      - image: circleci/golang:1.13

workflows:
  version: 2
  build_and_test:
    jobs:
      - golang_1.11
      - golang_1.12
      - golang_1.13
