version: 2

jobBase: &jobBase
  working_directory: /go/src/github.com/abice/gencheck
  steps:
      - checkout
      - run:
          name: Install Go Deps
          command: |
            curl https://glide.sh/get | sh
            go get -v github.com/kevinburke/go-bindata/...
            go get -v golang.org/x/tools/cmd/cover
            go get -v github.com/mattn/goveralls
            go get -v github.com/modocache/gover
            glide install
      - run:
          name: Build
          command: |
            make reinstall
      - run:
          name: Test
          command: |
            make test
            make cover
            make coveralls

jobs:
  golang_1.9:
    <<: *jobBase
    docker:
      - image: circleci/golang:1.9
  golang_1.10:
    <<: *jobBase
    docker:
      - image: circleci/golang:1.10
  golang_1.11:
    <<: *jobBase
    docker:
      - image: circleci/golang:1.11

workflows:
  version: 2
  build_and_test:
    jobs:
      - golang_1.9
      - golang_1.10
      - golang_1.11
